// the script...
#define SCRIPT_LEN 574

const char sScript[SCRIPT_LEN]="                                  INSPIRED BY HIS NEVER ENDING QUEST FOR PROGRESS, IN 2084 MAN PERFECTS THE ROBOTRONS: A ROBOT SPECIES SO ADVANCED THAT MAN IS INFERIOR TO HIS OWN CREATION. GUIDED BY THEIR INFALLIBLE LOGIC, THE ROBOTRONS CONCLUDE: THE HUMAN RACE IS INEFFICIENT, AND THEREFORE MUST BE DESTROYED.                                  YOU ARE THE LAST HOPE OF MANKIND. DUE TO A GENETIC ENGINEERING ERROR, YOU POSSESS SUPERHUMAN POWERS. YOUR MISSION IS TO STOP THE ROBOTRONS, AND SAVE THE LAST HUMAN FAMILY: MOMMY, DADDY, AND MIKEY.                                  ";

