// the script...
const char sScript[39][15]={
	"Inspired by his",
	"never ending   ",
	"quest for      ",
	"progress, in   ",
	"2084 man       ",
	"perfects the   ",
	"Robotrons: a   ",
	"robot species  ",
	"so advanced    ",
	"that man is    ",
	"inferior to his",
	"own creation.  ",
	"Guided by their",
	"infallible     ",
	"logic, the     ",
	"Robotrons      ",
	"conclude: The  ",
	"human race is  ",
	"inefficient,   ",
	"and therefore  ",
	"must be        ",
	"destroyed.     ",
	"               ",
	"You are the    ",
	"last hope of   ",
	"mankind. Due to",
	"a genetic      ",
	"engineering    ",
	"error, you     ",
	"possess        ",
	"superhuman     ",
	"powers. Your   ",
	"mission is to  ",
	"stop the       ",
	"Robotrons, and ",
	"save the last  ",
	"human family:  ",
	"Mommy, Daddy,  ",
	"and Mikey.     "
};

#define SCRIPT_LEN 38
